### ISSUE TITLE
one 👋 ?

### ISSUE THREAD

**Issue by ionurboz** [cferdinandi/events#4]
It's a nice, simple coding. But as a matter of fact, "one ();" function must be added, It will be very handsome :)

**Comment by ionurboz** [comment]
```
                        var one = function (types, selector, callback) {
				events.on(types, selector, function callbackWrapper(e){
					callback(e);
					events.off(types, selector, callbackWrapper);
				});
			}
```

I tested it in **Chrome**.

**Comment by cferdinandi** [comment]
Added under the name `once()`: https://github.com/cferdinandi/events#once
