### ISSUE TITLE
The types parameter requires comma separation but JSDoc says it requires space separation

### ISSUE THREAD

**Issue by kbav** [cferdinandi/events#5]
In the code and in the README, the JSDoc functions indicate the `types` parameter accepts multiple events with space separation ( `@param  {String}   types    The event type or types (space separated)` ). Your article on GMT indicates **comma separation**, however, and from what I understand of your code that seems to be the case. Just wanting to check!

I'm looking forward giving this library a go. Thank you for putting it together!

**Comment by cferdinandi** [comment]
The JSDoc is wrong. It was space separated originally, but I switched to comma-separated and forgot to update. Will do that now, thanks!
