### ISSUE TITLE
[BUG] It cannot catch and listen for "mouseleave" and "mouseenter" events.

### ISSUE THREAD

**Issue by ionurboz** [cferdinandi/events#9]
## [BUG] It cannot catch and listen for "mouseleave" and "mouseenter" events.

- As mentioned on this issue #7, some events cannot be caught by [events.js#L105](https://github.com/cferdinandi/events/blob/master/dist/events.js#L105). Because the `window` to which the event listener is attached does not need to listen to it and does not trigger any event.
- The following approach can be used to fix this problem,

```js
// If no event of this type yet, setup
if (!activeEvents[type]) {
   activeEvents[type] = [];

   ['mouseleave','mouseenter'].indexOf(type) >= 0 ?
   document.addEventListener(type, eventHandler, true) :
   window.addEventListener(type, eventHandler, true);
}
```

_**Note:** Some events such as `onstorage` only works on `window`. For this, we cannot set all of them as `document`._

----

Ok now I have tested this approach and I can confirm it works.
- If you have a better and simpler approach like #8, please let me know.
- Other events that might exhibit typical behavior such as `mouseleave` and `mouseenter` should be examined individually and a list made. (So they can be attached to `document` instead of `window`)

**Comment by cferdinandi** [comment]
Why was this closed?

**Comment by ionurboz** [comment]
@cferdinandi  

I have a new idea about this and this problem is out of date. I added a new issue. #10
